// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPuPGK-T95BVkj9Nn3bu8rCjp3w0EXNSM',
    appId: '1:303071323142:web:4a1ac821f3f36a2c6ccf87',
    messagingSenderId: '303071323142',
    projectId: 'mind-link-7a1cb',
    authDomain: 'mind-link-7a1cb.firebaseapp.com',
    storageBucket: 'mind-link-7a1cb.appspot.com',
    measurementId: 'G-F9RGJBE2NV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTRgn6apyKYai_Mp59kut13jHWiq7dUW4',
    appId: '1:303071323142:android:28670791962d7c5e6ccf87',
    messagingSenderId: '303071323142',
    projectId: 'mind-link-7a1cb',
    storageBucket: 'mind-link-7a1cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlsuXcSmaXc9AjdHXLofoKvgISY_FbY6M',
    appId: '1:303071323142:ios:233c0418f013572a6ccf87',
    messagingSenderId: '303071323142',
    projectId: 'mind-link-7a1cb',
    storageBucket: 'mind-link-7a1cb.appspot.com',
    iosBundleId: 'com.example.mindlinkk',
  );
}
